### PR TITLE
Much improved Links support, and Ofir's autocomplete requests

### PR DESCRIPTION
**Pull request by drorspei**
1. It's now possible to click on shell links like "<pyshell#11>". This was probably working once, but some code changed and it stopped doing so.
2. if you now use "??" on something, the output starts with a line including a link to the code, which is handy if you want to go edit it (or see it colored properly).
3. if you right click on a line in the output of "??" and select "Go to file/line" then it will actually go to the specific line! So it's now much easier to find and edit what you want.
4. I made Squeezer not lose file links after squeezing and expanding text.
5. autocomplete can now be configured to complete after pressing enter or tab once, which Ofir requested and I agree that it's nicer. The default behavior is unchanged.

### CODE REVIEW

**Comment by drorspei** [comment]
Something that I've always wanted - ability to squeeze code!
I realize that it's not a good habit to define long functions in the shell, but I do it, and I'm sure others do too.
Anyway the ability is configurable :)

**Comment by drorspei** [comment]
Extension configuration can now be made to require no restart!

I added an optional argument to idleConf.GetOption that tells it to remember the static member name of the extension's class. When configDialog wants to save updated options, those members that gave their name to idleConf.GetOption can now be immediately updated.

All the options that I personally added now use this feature.

**Comment by drorspei** [comment]
Menu key now opens the right click menu.
This isn't awfully useful, but sometimes I'm scrolling around with the keyboard and see a block I want to squeeze. Using the Ctrl-= sequence squeezes the bottom-most block, which isn't what I want.
Also in file editor we can now set breakpoints without using the mouse.

**Comment by ofir-reich** [comment]
This actually DOES seem super useful to me, especially for this squeezer option. Thanks!

**Comment by drorspei** [comment]
Step towards feature documentation: extension docstrings now appear in configDialog. I added docstrings to the extensions I know. 

We should probably have some standard for this, but that can wait. 

I couldn't get the frame to fill the window vertically, my experience with tkinter is limited, and the online documentation is no good.

**Comment by drorspei** [comment]
Keybinding methods of extensions are defined in the config-extensions.def file, and correspond to methods of extension classes. 

configDialog now shows the docstring of an event method when its associated key is selected in the KeysPage listbox. 

To see this in action select, for example, force-open-calltip.

**Comment by drorspei** [comment]
Alright, some more stuff.

1. Right click menu now has keyboard shortcuts.
2. Fixed a bug in squeezer: when trying to squeeze last output, and there are stderr and stdout, sometimes comparing the indexes as strings results in the wrong squeezing.
3. Made showing dict keys configurable and disabled by default.
4. Trying to autocomplete in a list/tuple getitem results in a tooltip of the object's length. This is configurable and disabled by default.
5. Added new extension: ExpressionEvaluator
this extension lets you select some text, right click, and select "Evaluate expression". A tooltip opens showing the result of evaluation.

Just today I was writing some code in an editor window and wanted to import a function. I forgot from which module it was in, so I just continued writing

    functionName.__module__

and evaluated it. Boom - I knew where it was. Removed the `.__module__` and added the import. Super easy, super fast.

Basically sometimes I'm browsing previously written code, either in shell or an editor window, and I want to know what something is. One way is to click "." and wait for AutoComplete to kick in and try to guess from the available completions. Another way is of course to go to the shell and actually run something. But those are annoying.

The function module example above has motivated me to extend ExpressionEvaluator to also add a right click menu option "Go to definition", like in some other IDEs. It will look for the line defining a particular function or class, like in the "??" command, and open an editor window there. It will also work for imports, so clicking at the end of `from numpy.linalg import solve` will open a window at the definition of the function solve (which incidentally I needed to check today). It's simple, and I'll do it soon.

**Comment by drorspei** [comment]
New feature: ability to configure ExpressionEvaluate to reevaluate the expression every x seconds and refresh the tooltip, as long as it's open.

The use case is this: you start looping through something and doing something heavy, only to realize it's going to take a while. You forgot to put tqdm, not even realizing you'll want it. Say you ran:

    for i in range(20):
        do_heavy_stuff()

Now you can select `i` and choose "Evaluate expression" from the right click menu. A tooltip showing the value `i` every, say, second will appear.

Though you can delegate the current thread to a background job and then repeatedly evaluate `i` yourself, it's much more verbose and painstaking.

The ability is configurable and disabled by default.

**Comment by ofir-reich** [comment]
Great!! I'm happy with how it works in ipython. I'll give it a try and say if it's suboptimal. :)

**Comment by drorspei** [comment]
cool :D

It's just that if we want it like in ipython, then we'll also want to see output row numbers so that Out[17] can work. But then idlespork will really look like ipython... 

That's not necessarily a bad idea. A while ago I was trying to get the underlying python in idlespork to be ipython, but it didn't work...
Could be cool though.

**Comment by ofir-reich** [comment]
How about the trick they had in the history module in the original idlefork/spork, where the prompt line had a ^[num]^ thing on it, that signified that the previous output is Out[num]?

**Comment by ofir-reich** [comment]
The links in shell don't work for me, I think. The code appears, but the link doesn't appear, as below.

```
>>> execfile('my_file.py")
>>> my_func??
File "{{{IDLESPORK_LINK:0}}}", line 729:
def my_func():
    [...]

```

**Comment by drorspei** [comment]
Fixed now on my fork, I'll finish more bugs and then submit a pull request

**Comment by ofir-reich** [comment]
> autocomplete can now be configured to complete after pressing enter or tab once, which Ofir requested and I agree that it's nicer. The default behavior is unchanged.

I'd love that. How do you configure it? Is it merged yet?

**Comment by drorspei** [comment]
yeah that's merged, you open configuration, go to the extensions tab, select AutoComplete, and uncheck `twotabstocomplete`, and check `entertocomplete`

**Pull request merged**
